// src/AgoraFold.Svelte/src/components/NavBar.svelte
<script lang="ts">
  import { navigate } from '../router'
  import { logout, user } from '../auth'
  import Link from './Link.svelte'

  let loggingOut = false

  async function handleLogout() {
    loggingOut = true
    try {
      await logout()
      navigate('/')
    } finally {
      loggingOut = false
    }
  }
</script>

<nav class="navbar">
  <Link href="/" className="brand">AgoraFold</Link>
  <div class="links">
    <Link href="/">Browse</Link>
    {#if $user}
      <Link href="/listings/new">Post a listing</Link>
      <Link href="/listings/mine">My listings</Link>
      <Link href="/conversations">Messages</Link>
      <span class="muted">{$user.displayName}</span>
      <button class="secondary" disabled={loggingOut} onclick={handleLogout}>Log out</button>
    {:else}
      <Link href="/login">Log in</Link>
      <Link href="/register">Register</Link>
    {/if}
  </div>
</nav>

// src/AgoraFold.React/src/components/NavBar.tsx
import { Link, useNavigate } from 'react-router-dom'
import { useAuth } from '../context/AuthContext'

export default function NavBar() {
  const { user, isAuthenticated, logout } = useAuth()
  const navigate = useNavigate()

  async function handleLogout() {
    await logout()
    navigate('/')
  }

  return (
    <nav className="navbar">
      <Link className="brand" to="/">AgoraFold</Link>
      <div className="links">
        <Link to="/">Browse</Link>
        {isAuthenticated ? (
          <>
            <Link to="/listings/new">Post a listing</Link>
            <Link to="/listings/mine">My listings</Link>
            <Link to="/conversations">Messages</Link>
            <span className="muted">{user?.displayName}</span>
            <button className="secondary" onClick={handleLogout}>Log out</button>
          </>
        ) : (
          <>
            <Link to="/login">Log in</Link>
            <Link to="/register">Register</Link>
          </>
        )}
      </div>
    </nav>
  )
}
