// src/AgoraFold.SolidJS/src/components/NavBar.tsx
import { A, useNavigate } from '@solidjs/router'
import { Show } from 'solid-js'
import { useAuth } from '../context/AuthContext'

export default function NavBar() {
  const { user, isAuthenticated, logout } = useAuth()
  const navigate = useNavigate()

  async function handleLogout() {
    await logout()
    navigate('/')
  }

  return (
    <nav class="navbar">
      <A class="brand" href="/">AgoraFold</A>
      <div class="links">
        <A href="/">Browse</A>
        <Show
          when={isAuthenticated()}
          fallback={
            <>
              <A href="/login">Log in</A>
              <A href="/register">Register</A>
            </>
          }
        >
          <A href="/listings/new">Post a listing</A>
          <A href="/listings/mine">My listings</A>
          <A href="/conversations">Messages</A>
          <span class="muted">{user()?.displayName}</span>
          <button class="secondary" onClick={handleLogout}>Log out</button>
        </Show>
      </div>
    </nav>
  )
}

// src/AgoraFold.React/src/components/NavBar.tsx
import { Link, useNavigate } from 'react-router-dom'
import { useAuth } from '../context/AuthContext'

export default function NavBar() {
  const { user, isAuthenticated, logout } = useAuth()
  const navigate = useNavigate()

  async function handleLogout() {
    await logout()
    navigate('/')
  }

  return (
    <nav className="navbar">
      <Link className="brand" to="/">AgoraFold</Link>
      <div className="links">
        <Link to="/">Browse</Link>
        {isAuthenticated ? (
          <>
            <Link to="/listings/new">Post a listing</Link>
            <Link to="/listings/mine">My listings</Link>
            <Link to="/conversations">Messages</Link>
            <span className="muted">{user?.displayName}</span>
            <button className="secondary" onClick={handleLogout}>Log out</button>
          </>
        ) : (
          <>
            <Link to="/login">Log in</Link>
            <Link to="/register">Register</Link>
          </>
        )}
      </div>
    </nav>
  )
}
