// src/AgoraFold.Vue/src/components/NavBar.vue
<script setup>
import { useRouter } from 'vue-router'
import { useAuthStore } from '../stores/auth'

const auth = useAuthStore()
const router = useRouter()

async function handleLogout() {
  await auth.logout()
  router.push({ name: 'browse' })
}
</script>

<template>
  <nav class="navbar">
    <RouterLink class="brand" :to="{ name: 'browse' }">AgoraFold</RouterLink>
    <div class="links">
      <RouterLink :to="{ name: 'browse' }">Browse</RouterLink>
      <template v-if="auth.isAuthenticated">
        <RouterLink :to="{ name: 'listing-new' }">Post a listing</RouterLink>
        <RouterLink :to="{ name: 'listing-mine' }">My listings</RouterLink>
        <RouterLink :to="{ name: 'conversations-inbox' }">Messages</RouterLink>
        <span class="muted">{{ auth.user.displayName }}</span>
        <button class="secondary" @click="handleLogout">Log out</button>
      </template>
      <template v-else>
        <RouterLink :to="{ name: 'login' }">Log in</RouterLink>
        <RouterLink :to="{ name: 'register' }">Register</RouterLink>
      </template>
    </div>
  </nav>
</template>

// src/AgoraFold.React/src/components/NavBar.tsx
import { Link, useNavigate } from 'react-router-dom'
import { useAuth } from '../context/AuthContext'

export default function NavBar() {
  const { user, isAuthenticated, logout } = useAuth()
  const navigate = useNavigate()

  async function handleLogout() {
    await logout()
    navigate('/')
  }

  return (
    <nav className="navbar">
      <Link className="brand" to="/">AgoraFold</Link>
      <div className="links">
        <Link to="/">Browse</Link>
        {isAuthenticated ? (
          <>
            <Link to="/listings/new">Post a listing</Link>
            <Link to="/listings/mine">My listings</Link>
            <Link to="/conversations">Messages</Link>
            <span className="muted">{user?.displayName}</span>
            <button className="secondary" onClick={handleLogout}>Log out</button>
          </>
        ) : (
          <>
            <Link to="/login">Log in</Link>
            <Link to="/register">Register</Link>
          </>
        )}
      </div>
    </nav>
  )
}
