// src/AgoraFold.Vue/src/components/Pagination.vue
<script setup lang="ts">
const props = defineProps<{
  page: number
  totalPages: number
  hasPreviousPage: boolean
  hasNextPage: boolean
}>()

const emit = defineEmits<{
  change: [page: number]
}>()
</script>

<template>
  <div class="pagination" v-if="totalPages > 1">
    <button class="secondary" :disabled="!hasPreviousPage" @click="emit('change', props.page - 1)">Previous</button>
    <span>Page {{ page }} of {{ totalPages }}</span>
    <button class="secondary" :disabled="!hasNextPage" @click="emit('change', props.page + 1)">Next</button>
  </div>
</template>

// src/AgoraFold.React/src/components/Pagination.tsx
interface PaginationProps {
  page: number
  totalPages: number
  hasPreviousPage: boolean
  hasNextPage: boolean
  onChange: (page: number) => void
}

export default function Pagination({ page, totalPages, hasPreviousPage, hasNextPage, onChange }: PaginationProps) {
  if (totalPages <= 1) return null

  return (
    <div className="pagination">
      <button className="secondary" disabled={!hasPreviousPage} onClick={() => onChange(page - 1)}>
        Previous
      </button>
      <span>Page {page} of {totalPages}</span>
      <button className="secondary" disabled={!hasNextPage} onClick={() => onChange(page + 1)}>
        Next
      </button>
    </div>
  )
}
