// src/AgoraFold.SolidJS/src/components/RequireAuth.tsx
import { Navigate, useLocation } from '@solidjs/router'
import { Show, type JSX } from 'solid-js'
import { useAuth } from '../context/AuthContext'

export default function RequireAuth(props: { children: JSX.Element }) {
  const { isAuthenticated, hydrated } = useAuth()
  const location = useLocation()

  return (
    <Show when={hydrated()}>
      <Show
        when={isAuthenticated()}
        fallback={<Navigate href={`/login?returnUrl=${encodeURIComponent(location.pathname + location.search)}`} />}
      >
        {props.children}
      </Show>
    </Show>
  )
}

// src/AgoraFold.React/src/components/RequireAuth.tsx
import type { ReactNode } from 'react'
import { Navigate, useLocation } from 'react-router-dom'
import { useAuth } from '../context/AuthContext'

export default function RequireAuth({ children }: { children: ReactNode }) {
  const { isAuthenticated, hydrated } = useAuth()
  const location = useLocation()

  if (!hydrated) return null

  if (!isAuthenticated) {
    const returnUrl = `${location.pathname}${location.search}`
    return <Navigate to={`/login?returnUrl=${encodeURIComponent(returnUrl)}`} replace />
  }

  return children
}
