// src/AgoraFold.SolidJS/src/pages/BrowsePage.tsx
import { createEffect, createSignal, For, Show, onMount } from 'solid-js'
import { useSearchParams } from '@solidjs/router'
import * as listingsApi from '../api/listings'
import * as categoriesApi from '../api/categories'
import ListingCard from '../components/ListingCard'
import Pagination from '../components/Pagination'
import type { Category, PagedListings } from '../api/types'

function firstParam(value: string | string[] | undefined): string {
  return (Array.isArray(value) ? value[0] : value) ?? ''
}

export default function BrowsePage() {
  const [searchParams, setSearchParams] = useSearchParams()
  const [categories, setCategories] = createSignal<Category[]>([])
  const [result, setResult] = createSignal<PagedListings | null>(null)
  const [loading, setLoading] = createSignal(true)

  const [categoryId, setCategoryId] = createSignal(firstParam(searchParams.categoryId))
  const [searchTerm, setSearchTerm] = createSignal(firstParam(searchParams.searchTerm))

  onMount(() => {
    categoriesApi.getAll().then(setCategories)
  })

  createEffect(() => {
    const page = Number(firstParam(searchParams.page) || 1)
    const categoryIdParam = firstParam(searchParams.categoryId)
    const searchTermParam = firstParam(searchParams.searchTerm)

    setLoading(true)
    listingsApi
      .browse({ categoryId: categoryIdParam || undefined, searchTerm: searchTermParam || undefined, page })
      .then((data) => {
        setResult(data)
        setLoading(false)
      })
  })

  function applyFilters(e: SubmitEvent) {
    e.preventDefault()
    setSearchParams({ categoryId: categoryId() || undefined, searchTerm: searchTerm() || undefined, page: undefined })
  }

  function goToPage(page: number) {
    setSearchParams({ page: String(page) })
  }

  return (
    <>
      <h1>Browse listings</h1>

      <form class="filters" onSubmit={applyFilters}>
        <label>
          Category
          <select value={categoryId()} onChange={(e) => setCategoryId(e.currentTarget.value)}>
            <option value="">All categories</option>
            <For each={categories()}>{(c) => <option value={c.id}>{c.name}</option>}</For>
          </select>
        </label>
        <label>
          Search
          <input
            value={searchTerm()}
            onInput={(e) => setSearchTerm(e.currentTarget.value)}
            type="text"
            placeholder="Search listings"
          />
        </label>
        <button type="submit">Apply</button>
      </form>

      <Show when={!loading()} fallback={<p>Loading...</p>}>
        <Show when={result()}>
          {(result) => (
            <>
              <Show when={result().items.length === 0}>
                <p class="muted">No listings found.</p>
              </Show>
              <ul class="listing-grid">
                <For each={result().items}>{(listing) => <li><ListingCard listing={listing} /></li>}</For>
              </ul>
              <Pagination
                page={result().page}
                totalPages={result().totalPages}
                hasPreviousPage={result().hasPreviousPage}
                hasNextPage={result().hasNextPage}
                onChange={goToPage}
              />
            </>
          )}
        </Show>
      </Show>
    </>
  )
}

// src/AgoraFold.React/src/pages/BrowsePage.tsx
import { useEffect, useState, type FormEvent } from 'react'
import { useSearchParams } from 'react-router-dom'
import * as listingsApi from '../api/listings'
import * as categoriesApi from '../api/categories'
import ListingCard from '../components/ListingCard'
import Pagination from '../components/Pagination'
import type { Category, PagedListings } from '../api/types'

export default function BrowsePage() {
  const [searchParams, setSearchParams] = useSearchParams()
  const [categories, setCategories] = useState<Category[]>([])
  const [result, setResult] = useState<PagedListings | null>(null)
  const [loading, setLoading] = useState(true)

  const [categoryId, setCategoryId] = useState(searchParams.get('categoryId') ?? '')
  const [searchTerm, setSearchTerm] = useState(searchParams.get('searchTerm') ?? '')

  useEffect(() => {
    categoriesApi.getAll().then(setCategories)
  }, [])

  useEffect(() => {
    setLoading(true)
    const page = Number(searchParams.get('page') ?? 1)
    listingsApi
      .browse({
        categoryId: searchParams.get('categoryId') || undefined,
        searchTerm: searchParams.get('searchTerm') || undefined,
        page,
      })
      .then((data) => {
        setResult(data)
        setLoading(false)
      })
  }, [searchParams])

  function applyFilters(e: FormEvent) {
    e.preventDefault()
    const next = new URLSearchParams()
    if (categoryId) next.set('categoryId', categoryId)
    if (searchTerm) next.set('searchTerm', searchTerm)
    setSearchParams(next)
  }

  function goToPage(page: number) {
    const next = new URLSearchParams(searchParams)
    next.set('page', String(page))
    setSearchParams(next)
  }

  return (
    <>
      <h1>Browse listings</h1>

      <form className="filters" onSubmit={applyFilters}>
        <label>
          Category
          <select value={categoryId} onChange={(e) => setCategoryId(e.target.value)}>
            <option value="">All categories</option>
            {categories.map((c) => (
              <option key={c.id} value={c.id}>
                {c.name}
              </option>
            ))}
          </select>
        </label>
        <label>
          Search
          <input
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            type="text"
            placeholder="Search listings"
          />
        </label>
        <button type="submit">Apply</button>
      </form>

      {loading ? (
        <p>Loading...</p>
      ) : result ? (
        <>
          {result.items.length === 0 && <p className="muted">No listings found.</p>}
          <ul className="listing-grid">
            {result.items.map((listing) => (
              <li key={listing.id}>
                <ListingCard listing={listing} />
              </li>
            ))}
          </ul>
          <Pagination
            page={result.page}
            totalPages={result.totalPages}
            hasPreviousPage={result.hasPreviousPage}
            hasNextPage={result.hasNextPage}
            onChange={goToPage}
          />
        </>
      ) : null}
    </>
  )
}
