// src/AgoraFold.Svelte/src/pages/MyListingsPage.svelte
<script lang="ts">
  import { onMount } from 'svelte'
  import * as listingsApi from '../api/listings'
  import type { ListingSummary } from '../api/types'
  import Link from '../components/Link.svelte'
  import ListingCard from '../components/ListingCard.svelte'

  let listings: ListingSummary[] = []

  onMount(() => {
    void listingsApi.getMine().then((loadedListings) => {
      listings = loadedListings
    })
  })
</script>

<h1>My listings</h1>
<Link href="/listings/new">Post a new listing</Link>

{#if listings.length === 0}<p class="muted">You haven't posted any listings yet.</p>{/if}
<ul class="listing-grid">
  {#each listings as listing (listing.id)}
    <li><ListingCard {listing} /></li>
  {/each}
</ul>

// src/AgoraFold.React/src/pages/MyListingsPage.tsx
import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import * as listingsApi from '../api/listings'
import ListingCard from '../components/ListingCard'
import type { ListingSummary } from '../api/types'

export default function MyListingsPage() {
  const [listings, setListings] = useState<ListingSummary[]>([])

  useEffect(() => {
    listingsApi.getMine().then(setListings)
  }, [])

  return (
    <>
      <h1>My listings</h1>
      <Link to="/listings/new">Post a new listing</Link>

      {listings.length === 0 && <p className="muted">You haven't posted any listings yet.</p>}
      <ul className="listing-grid">
        {listings.map((listing) => (
          <li key={listing.id}>
            <ListingCard listing={listing} />
          </li>
        ))}
      </ul>
    </>
  )
}
