// src/AgoraFold.React/src/components/Pagination.tsx
interface PaginationProps {
  page: number
  totalPages: number
  hasPreviousPage: boolean
  hasNextPage: boolean
  onChange: (page: number) => void
}

export default function Pagination({ page, totalPages, hasPreviousPage, hasNextPage, onChange }: PaginationProps) {
  if (totalPages <= 1) return null

  return (
    <div className="pagination">
      <button className="secondary" disabled={!hasPreviousPage} onClick={() => onChange(page - 1)}>
        Previous
      </button>
      <span>Page {page} of {totalPages}</span>
      <button className="secondary" disabled={!hasNextPage} onClick={() => onChange(page + 1)}>
        Next
      </button>
    </div>
  )
}

// src/AgoraFold.SolidJS/src/components/Pagination.tsx
import { Show } from 'solid-js'

interface PaginationProps {
  page: number
  totalPages: number
  hasPreviousPage: boolean
  hasNextPage: boolean
  onChange: (page: number) => void
}

export default function Pagination(props: PaginationProps) {
  return (
    <Show when={props.totalPages > 1}>
      <div class="pagination">
        <button class="secondary" disabled={!props.hasPreviousPage} onClick={() => props.onChange(props.page - 1)}>
          Previous
        </button>
        <span>Page {props.page} of {props.totalPages}</span>
        <button class="secondary" disabled={!props.hasNextPage} onClick={() => props.onChange(props.page + 1)}>
          Next
        </button>
      </div>
    </Show>
  )
}
