// src/AgoraFold.SolidJS/src/App.tsx
import { Route } from '@solidjs/router'
import RequireAuth from './components/RequireAuth'
import BrowsePage from './pages/BrowsePage'
import LoginPage from './pages/LoginPage'
import RegisterPage from './pages/RegisterPage'
import ListingFormPage from './pages/ListingFormPage'
import ListingDetailPage from './pages/ListingDetailPage'
import MyListingsPage from './pages/MyListingsPage'
import ConversationsInboxPage from './pages/ConversationsInboxPage'
import ConversationThreadPage from './pages/ConversationThreadPage'

export default function App() {
  return (
    <>
      <Route path="/" component={BrowsePage} />
      <Route path="/login" component={LoginPage} />
      <Route path="/register" component={RegisterPage} />
      <Route path="/listings/new" component={() => <RequireAuth><ListingFormPage /></RequireAuth>} />
      <Route path="/listings/mine" component={() => <RequireAuth><MyListingsPage /></RequireAuth>} />
      <Route path="/listings/:id/edit" component={() => <RequireAuth><ListingFormPage /></RequireAuth>} />
      <Route path="/listings/:id" component={ListingDetailPage} />
      <Route path="/conversations" component={() => <RequireAuth><ConversationsInboxPage /></RequireAuth>} />
      <Route path="/conversations/:id" component={() => <RequireAuth><ConversationThreadPage /></RequireAuth>} />
    </>
  )
}

// src/AgoraFold.Svelte/src/App.svelte
<script lang="ts">
  import { onMount } from 'svelte'
  import { hydrated, hydrate, user } from './auth'
  import { navigate, route } from './router'
  import NavBar from './components/NavBar.svelte'
  import BrowsePage from './pages/BrowsePage.svelte'
  import LoginPage from './pages/LoginPage.svelte'
  import RegisterPage from './pages/RegisterPage.svelte'
  import ListingFormPage from './pages/ListingFormPage.svelte'
  import ListingDetailPage from './pages/ListingDetailPage.svelte'
  import MyListingsPage from './pages/MyListingsPage.svelte'
  import ConversationsInboxPage from './pages/ConversationsInboxPage.svelte'
  import ConversationThreadPage from './pages/ConversationThreadPage.svelte'

  const protectedPaths = ['/listings/new', '/listings/mine', '/conversations']

  onMount(() => {
    void hydrate()
  })

  $: isProtected = protectedPaths.includes($route.path) || /^\/listings\/\d+\/edit$/.test($route.path) || /^\/conversations\/\d+$/.test($route.path)
  $: if ($hydrated && !$user && isProtected) {
    const returnUrl = `${$route.path}${$route.query.toString() ? `?${$route.query.toString()}` : ''}`
    navigate(`/login?returnUrl=${encodeURIComponent(returnUrl)}`, true)
  }

  function isListingEdit() {
    return /^\/listings\/\d+\/edit$/.test($route.path)
  }
</script>

<NavBar />
<main class="container">
  {#if !$hydrated}
    <p>Loading...</p>
  {:else if isProtected && !$user}
    <p>Redirecting to log in...</p>
  {:else if $route.path === '/'}
    <BrowsePage />
  {:else if $route.path === '/login'}
    <LoginPage />
  {:else if $route.path === '/register'}
    <RegisterPage />
  {:else if $route.path === '/listings/new' || isListingEdit()}
    <ListingFormPage />
  {:else if /^\/listings\/\d+$/.test($route.path)}
    <ListingDetailPage />
  {:else if $route.path === '/listings/mine'}
    <MyListingsPage />
  {:else if $route.path === '/conversations'}
    <ConversationsInboxPage />
  {:else if /^\/conversations\/\d+$/.test($route.path)}
    <ConversationThreadPage />
  {:else}
    <BrowsePage />
  {/if}
</main>
