// src/AgoraFold.React/src/pages/ConversationsInboxPage.tsx
import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import * as conversationsApi from '../api/conversations'
import type { ConversationSummary } from '../api/types'

export default function ConversationsInboxPage() {
  const [conversations, setConversations] = useState<ConversationSummary[]>([])

  useEffect(() => {
    conversationsApi.getInbox().then(setConversations)
  }, [])

  return (
    <>
      <h1>Messages</h1>
      {conversations.length === 0 && <p className="muted">No conversations yet.</p>}
      <ul className="conversation-list">
        {conversations.map((c) => (
          <li key={c.id}>
            <Link to={`/conversations/${c.id}`}>
              <strong>{c.listingTitle}</strong> &middot; {c.otherPartyDisplayName}
            </Link>
            <p className="muted">
              {c.lastMessageIsMine ? 'You: ' : ''}
              {c.lastMessageBody}
            </p>
          </li>
        ))}
      </ul>
    </>
  )
}

// src/AgoraFold.Svelte/src/pages/ConversationsInboxPage.svelte
<script lang="ts">
  import { onMount } from 'svelte'
  import * as conversationsApi from '../api/conversations'
  import type { ConversationSummary } from '../api/types'
  import Link from '../components/Link.svelte'

  let conversations: ConversationSummary[] = []

  onMount(() => {
    void conversationsApi.getInbox().then((loadedConversations) => {
      conversations = loadedConversations
    })
  })
</script>

<h1>Messages</h1>
{#if conversations.length === 0}<p class="muted">No conversations yet.</p>{/if}
<ul class="conversation-list">
  {#each conversations as conversation (conversation.id)}
    <li>
      <Link href={`/conversations/${conversation.id}`}>
        <strong>{conversation.listingTitle}</strong> &middot; {conversation.otherPartyDisplayName}
      </Link>
      <p class="muted">{conversation.lastMessageIsMine ? 'You: ' : ''}{conversation.lastMessageBody}</p>
    </li>
  {/each}
</ul>
