// src/AgoraFold.Svelte/src/components/ListingCard.svelte
<script lang="ts">
  import { imageUrl } from '../api/client'
  import type { ListingSummary } from '../api/types'
  import Link from './Link.svelte'

  export let listing: ListingSummary
</script>

<Link href={`/listings/${listing.id}`} className="listing-card">
  {#if listing.thumbnailUrl}
    <img src={imageUrl(listing.thumbnailUrl)} alt={listing.title} />
  {:else}
    <div class="thumbnail-placeholder"></div>
  {/if}
  <div class="body">
    <strong>{listing.title}</strong>
    <div class="muted">{listing.categoryName}</div>
    {#if listing.price != null}<div>${listing.price}</div>{/if}
  </div>
</Link>

// src/AgoraFold.Vue/src/components/ListingCard.vue
<script setup lang="ts">
import { imageUrl } from '../api/client'
import type { ListingSummary } from '../api/types'

defineProps<{
  listing: ListingSummary
}>()
</script>

<template>
  <RouterLink class="listing-card" :to="{ name: 'listing-detail', params: { id: listing.id } }">
    <img v-if="listing.thumbnailUrl" :src="imageUrl(listing.thumbnailUrl)" :alt="listing.title" />
    <div v-else class="thumbnail-placeholder" />
    <div class="body">
      <strong>{{ listing.title }}</strong>
      <div class="muted">{{ listing.categoryName }}</div>
      <div v-if="listing.price != null">${{ listing.price }}</div>
    </div>
  </RouterLink>
</template>
