// src/AgoraFold.React/src/components/Pagination.tsx
interface PaginationProps {
  page: number
  totalPages: number
  hasPreviousPage: boolean
  hasNextPage: boolean
  onChange: (page: number) => void
}

export default function Pagination({ page, totalPages, hasPreviousPage, hasNextPage, onChange }: PaginationProps) {
  if (totalPages <= 1) return null

  return (
    <div className="pagination">
      <button className="secondary" disabled={!hasPreviousPage} onClick={() => onChange(page - 1)}>
        Previous
      </button>
      <span>Page {page} of {totalPages}</span>
      <button className="secondary" disabled={!hasNextPage} onClick={() => onChange(page + 1)}>
        Next
      </button>
    </div>
  )
}

// src/AgoraFold.Svelte/src/components/Pagination.svelte
<script lang="ts">
  export let page: number
  export let totalPages: number
  export let hasPreviousPage: boolean
  export let hasNextPage: boolean
  export let onChange: (page: number) => void
</script>

{#if totalPages > 1}
  <div class="pagination">
    <button class="secondary" disabled={!hasPreviousPage} onclick={() => onChange(page - 1)}>Previous</button>
    <span>Page {page} of {totalPages}</span>
    <button class="secondary" disabled={!hasNextPage} onclick={() => onChange(page + 1)}>Next</button>
  </div>
{/if}
