// src/AgoraFold.Svelte/src/pages/ListingFormPage.svelte
<script lang="ts">
  import { onMount } from 'svelte'
  import * as categoriesApi from '../api/categories'
  import * as listingsApi from '../api/listings'
  import { ApiError, imageUrl } from '../api/client'
  import type { Category, ListingImage } from '../api/types'
  import { navigate, route } from '../router'

  interface FormState {
    title: string
    description: string
    price: number | string
    categoryId: number | string
  }

  let categories: Category[] = []
  let images: ListingImage[] = []
  let errors: string[] = []
  let saving = false
  let form: FormState = { title: '', description: '', price: '', categoryId: '' }
  let newImageFiles: FileList | null = null
  let loadedId = ''

  $: id = $route.params.id
  $: isEdit = /^\/listings\/\d+\/edit$/.test($route.path)

  onMount(() => {
    void categoriesApi.getAll().then((loadedCategories) => {
      categories = loadedCategories
      if (!isEdit && loadedCategories.length) form = { ...form, categoryId: loadedCategories[0].id }
    })
  })

  $: if (isEdit && id && id !== loadedId) {
    loadedId = id
    void listingsApi.getDetail(id).then((listing) => {
      form = {
        title: listing.title,
        description: listing.description,
        price: listing.price ?? '',
        categoryId: listing.categoryId,
      }
      images = listing.images
    })
  }

  function errorMessages(exception: unknown): string[] {
    if (exception instanceof ApiError && exception.errors.length) return exception.errors
    return [(exception as Error).message]
  }

  async function submit(event: SubmitEvent) {
    event.preventDefault()
    saving = true
    errors = []
    try {
      if (isEdit) {
        await listingsApi.update(id!, form)
        navigate(`/listings/${id}`)
      } else {
        const created = await listingsApi.create({ ...form, images: newImageFiles })
        errors = created.imageErrors ?? []
        navigate(`/listings/${created.id}`)
      }
    } catch (exception) {
      errors = errorMessages(exception)
    } finally {
      saving = false
    }
  }

  async function addMoreImages() {
    if (!newImageFiles?.length || !id) return
    errors = []
    try {
      images = await listingsApi.addImages(id, newImageFiles)
      newImageFiles = null
    } catch (exception) {
      errors = errorMessages(exception)
    }
  }

  async function removeImage(imageId: number) {
    if (!id) return
    await listingsApi.deleteImage(id, imageId)
    images = images.filter((image) => image.id !== imageId)
  }

  function onImageFilesChange(event: Event) {
    newImageFiles = (event.currentTarget as HTMLInputElement).files
  }
</script>

<h1>{isEdit ? 'Edit listing' : 'Post a listing'}</h1>

{#if errors.length}
  <ul class="error-list">
    {#each errors as error}<li>{error}</li>{/each}
  </ul>
{/if}

<form onsubmit={submit}>
  <label>
    Title
    <input bind:value={form.title} type="text" required maxlength="200" />
  </label>
  <label>
    Description
    <textarea bind:value={form.description} required maxlength="4000"></textarea>
  </label>
  <label>
    Price (optional)
    <input bind:value={form.price} type="number" min="0" step="0.01" />
  </label>
  <label>
    Category
    <select bind:value={form.categoryId} required>
      {#each categories as category}
        <option value={category.id}>{category.name}</option>
      {/each}
    </select>
  </label>
  {#if !isEdit}
    <label>
      Images
      <input type="file" accept="image/*" multiple onchange={onImageFilesChange} />
    </label>
  {/if}
  <button type="submit" disabled={saving}>{isEdit ? 'Save changes' : 'Post listing'}</button>
</form>

{#if isEdit}
  <h2>Images</h2>
  <ul class="image-gallery">
    {#each images as image (image.id)}
      <li>
        <img src={imageUrl(image.url)} alt="" />
        <button class="danger" onclick={() => removeImage(image.id)}>Remove</button>
      </li>
    {/each}
  </ul>
  <label>
    Add images
    <input type="file" accept="image/*" multiple onchange={onImageFilesChange} />
  </label>
  <button class="secondary" onclick={addMoreImages}>Upload</button>
{/if}

// src/AgoraFold.SolidJS/src/pages/ListingFormPage.tsx
import { createEffect, createSignal, For, Show } from 'solid-js'
import { useNavigate, useParams } from '@solidjs/router'
import * as listingsApi from '../api/listings'
import * as categoriesApi from '../api/categories'
import { imageUrl, ApiError } from '../api/client'
import type { Category, ListingImage } from '../api/types'

interface FormState {
  title: string
  description: string
  price: number | string
  categoryId: number | string
}

function errorMessages(err: unknown): string[] {
  if (err instanceof ApiError && err.errors.length) return err.errors
  return [(err as Error).message]
}

export default function ListingFormPage() {
  const params = useParams<{ id: string }>()
  const navigate = useNavigate()
  const isEdit = () => !!params.id

  const [categories, setCategories] = createSignal<Category[]>([])
  const [images, setImages] = createSignal<ListingImage[]>([])
  const [errors, setErrors] = createSignal<string[]>([])
  const [saving, setSaving] = createSignal(false)
  const [form, setForm] = createSignal<FormState>({ title: '', description: '', price: '', categoryId: '' })
  const [newImageFiles, setNewImageFiles] = createSignal<FileList | null>(null)

  createEffect(() => {
    const id = params.id
    categoriesApi.getAll().then((loadedCategories) => {
      setCategories(loadedCategories)
      if (id) {
        listingsApi.getDetail(id).then((listing) => {
          setForm({
            title: listing.title,
            description: listing.description,
            price: listing.price ?? '',
            categoryId: listing.categoryId,
          })
          setImages(listing.images)
        })
      } else if (loadedCategories.length) {
        setForm((f) => ({ ...f, categoryId: loadedCategories[0].id }))
      }
    })
  })

  async function submit(e: SubmitEvent) {
    e.preventDefault()
    setSaving(true)
    setErrors([])
    try {
      if (isEdit()) {
        await listingsApi.update(params.id, form())
        navigate(`/listings/${params.id}`)
      } else {
        const created = await listingsApi.create({ ...form(), images: newImageFiles() })
        setErrors(created.imageErrors ?? [])
        navigate(`/listings/${created.id}`)
      }
    } catch (err) {
      setErrors(errorMessages(err))
    } finally {
      setSaving(false)
    }
  }

  async function addMoreImages() {
    const files = newImageFiles()
    if (!files?.length) return
    setErrors([])
    try {
      setImages(await listingsApi.addImages(params.id, files))
      setNewImageFiles(null)
    } catch (err) {
      setErrors(errorMessages(err))
    }
  }

  async function removeImage(imageId: number) {
    await listingsApi.deleteImage(params.id, imageId)
    setImages((imgs) => imgs.filter((i) => i.id !== imageId))
  }

  function onImageFilesChange(e: Event & { currentTarget: HTMLInputElement }) {
    setNewImageFiles(e.currentTarget.files)
  }

  return (
    <>
      <h1>{isEdit() ? 'Edit listing' : 'Post a listing'}</h1>

      <Show when={errors().length > 0}>
        <ul class="error-list">
          <For each={errors()}>{(e) => <li>{e}</li>}</For>
        </ul>
      </Show>

      <form onSubmit={submit}>
        <label>
          Title
          <input
            value={form().title}
            onInput={(e) => setForm((f) => ({ ...f, title: e.currentTarget.value }))}
            type="text"
            required
            maxlength={200}
          />
        </label>
        <label>
          Description
          <textarea
            value={form().description}
            onInput={(e) => setForm((f) => ({ ...f, description: e.currentTarget.value }))}
            required
            maxlength={4000}
          />
        </label>
        <label>
          Price (optional)
          <input
            value={form().price}
            onInput={(e) => setForm((f) => ({ ...f, price: e.currentTarget.value }))}
            type="number"
            min="0"
            step="0.01"
          />
        </label>
        <label>
          Category
          <select
            value={form().categoryId}
            onChange={(e) => setForm((f) => ({ ...f, categoryId: e.currentTarget.value }))}
            required
          >
            <For each={categories()}>{(c) => <option value={c.id}>{c.name}</option>}</For>
          </select>
        </label>
        <Show when={!isEdit()}>
          <label>
            Images
            <input type="file" accept="image/*" multiple onChange={onImageFilesChange} />
          </label>
        </Show>
        <button type="submit" disabled={saving()}>
          {isEdit() ? 'Save changes' : 'Post listing'}
        </button>
      </form>

      <Show when={isEdit()}>
        <h2>Images</h2>
        <ul class="image-gallery">
          <For each={images()}>
            {(image) => (
              <li>
                <img src={imageUrl(image.url)} alt="" />
                <button class="danger" onClick={() => removeImage(image.id)}>
                  Remove
                </button>
              </li>
            )}
          </For>
        </ul>
        <label>
          Add images
          <input type="file" accept="image/*" multiple onChange={onImageFilesChange} />
        </label>
        <button class="secondary" onClick={addMoreImages}>
          Upload
        </button>
      </Show>
    </>
  )
}
