// src/AgoraFold.React/src/pages/RegisterPage.tsx
import { useState, type FormEvent } from 'react'
import { useNavigate } from 'react-router-dom'
import { useAuth } from '../context/AuthContext'
import { ApiError } from '../api/client'

export default function RegisterPage() {
  const navigate = useNavigate()
  const { register } = useAuth()

  const [email, setEmail] = useState('')
  const [displayName, setDisplayName] = useState('')
  const [password, setPassword] = useState('')
  const [errors, setErrors] = useState<string[]>([])
  const [submitting, setSubmitting] = useState(false)

  async function submit(e: FormEvent) {
    e.preventDefault()
    setSubmitting(true)
    setErrors([])
    try {
      await register(email, displayName, password)
      navigate('/')
    } catch (err) {
      setErrors(err instanceof ApiError && err.errors.length ? err.errors : [(err as Error).message])
    } finally {
      setSubmitting(false)
    }
  }

  return (
    <>
      <h1>Register</h1>
      {errors.length > 0 && (
        <ul className="error-list">
          {errors.map((e, i) => (
            <li key={i}>{e}</li>
          ))}
        </ul>
      )}
      <form onSubmit={submit}>
        <label>
          Email
          <input
            value={email}
            onChange={(e) => setEmail(e.target.value)}
            type="email"
            required
            autoComplete="username"
          />
        </label>
        <label>
          Display name
          <input value={displayName} onChange={(e) => setDisplayName(e.target.value)} type="text" required />
        </label>
        <label>
          Password
          <input
            value={password}
            onChange={(e) => setPassword(e.target.value)}
            type="password"
            required
            autoComplete="new-password"
          />
        </label>
        <button type="submit" disabled={submitting}>
          Register
        </button>
      </form>
    </>
  )
}

// src/AgoraFold.SolidJS/src/pages/RegisterPage.tsx
import { createSignal, For, Show } from 'solid-js'
import { useNavigate } from '@solidjs/router'
import { useAuth } from '../context/AuthContext'
import { ApiError } from '../api/client'

export default function RegisterPage() {
  const navigate = useNavigate()
  const { register } = useAuth()

  const [email, setEmail] = createSignal('')
  const [displayName, setDisplayName] = createSignal('')
  const [password, setPassword] = createSignal('')
  const [errors, setErrors] = createSignal<string[]>([])
  const [submitting, setSubmitting] = createSignal(false)

  async function submit(e: SubmitEvent) {
    e.preventDefault()
    setSubmitting(true)
    setErrors([])
    try {
      await register(email(), displayName(), password())
      navigate('/')
    } catch (err) {
      setErrors(err instanceof ApiError && err.errors.length ? err.errors : [(err as Error).message])
    } finally {
      setSubmitting(false)
    }
  }

  return (
    <>
      <h1>Register</h1>
      <Show when={errors().length > 0}>
        <ul class="error-list">
          <For each={errors()}>{(e) => <li>{e}</li>}</For>
        </ul>
      </Show>
      <form onSubmit={submit}>
        <label>
          Email
          <input
            value={email()}
            onInput={(e) => setEmail(e.currentTarget.value)}
            type="email"
            required
            autocomplete="username"
          />
        </label>
        <label>
          Display name
          <input value={displayName()} onInput={(e) => setDisplayName(e.currentTarget.value)} type="text" required />
        </label>
        <label>
          Password
          <input
            value={password()}
            onInput={(e) => setPassword(e.currentTarget.value)}
            type="password"
            required
            autocomplete="new-password"
          />
        </label>
        <button type="submit" disabled={submitting()}>
          Register
        </button>
      </form>
    </>
  )
}
